### ISSUE TITLE
Mouse back button not working

### ISSUE THREAD

**Issue by leobewater** [inertiajs/inertia-laravel#113]
Inertiajs saves me a lot of time building SPA. Thank you so much for making this happen.

One thing I found out is that the mouse back button doesn't go back to the previous page. Please help.

**Comment by claudiodekker** [comment]
Hi Leo,

I just checked on one of my own Inertia installations, but there everything seems to work fine when I click the back button on my browser. Could you provide more details (like what browser you're using, what Inertia front-end package you're using (Vue, React etc.), and possibly an example web page on which this occurs?

Thanks!

**Comment by claudiodekker** [comment]
Hi,

Since it's been a while since I replied to this question with no further follow-up, I'm assuming that you solved your issue or that it is no longer relevant. As such, I'll be closing this issue. If you feel like your issue is still relevant but you just haven't had the time to reply to it, feel free to re-open the issue at any point by leaving a comment.

Thanks!
