### ISSUE TITLE
Inertia remove all childs in app div

### ISSUE THREAD

**Issue by lucabecchetti** [inertiajs/inertia-laravel#115]
Hi guys, I have these inside my app.blade.php:

```html
<div id="app" data-page="{{ json_encode($page) }}">
    @include('layouts.sidebar')
    <c-wrapper>
        @include('layouts.header')
        <div class="c-body">
            <main class="c-main">
                    @yield('content')           
            </main>
        </div>
    </c-wrapper>
</div>
```

the problem is that when I mount inertia component all app child did removed, how con I mount intertia component at the place of @yield content 
????

**Comment by claudiodekker** [comment]
Hi,

This has to do with the way your front-end library (whether Vue, React or otherwise) is configured. The way that these libraries work, is that they attach themselves to a single DOM element, and fully control it.

Here's a description of how this works internally, and why they do this:
> When you change the DOM in any way, your browser considers the entire nested element tree to be _dirty_, after which it starts re-calculating where everything is supposed to go to properly reflect the change you made. It does this in a couple of steps: [First, it figures out what shape everything is supposed to be by reading through the CSS specification rules and your own CSS definitions (the "render tree"), then it recalculates where everything is supposed to go (the "box model"), and finally it starts 'painting' the actual HTML/CSS into pixels on your screen](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction). 
>
>This last "painting" step is considered to be relatively slow and heavy on your browser, and as such, reactive JS libraries try to minimize the time spent in this step, by introducing a so-called 'Virtual DOM', which you can basically imagine to be a big javascript object that represents the state of all nested elements. This includes each element's attributes (type, class, style and content) and allows the library to quickly 'know' what has changed and what hasn't. After it knows what's changed, it goes ahead and applies all of these changes on the actual browser DOM in one go, resulting in that the browser itself has to do the least amount of 'repainting' possible. 
>
>Now, let's say you make a change to the HTML in a component (by clicking on a button or something). Instead of directly modifying the DOM, the change itself gets sent to the Library's "core", which then applies it to the 'Virtual DOM'. The library then 'queues' all changes in that moment, [waits until the next tick](https://vuejsdevelopers.com/2019/01/22/vue-what-is-next-tick/), and applies all changes the actual DOM in one go, with as a result that the browser only has to do an update once, after which you see the changes appear on your screen.
>
>This also explains why libraries like JQuery or Angular feel so slow and heavy.

When the library starts comparing what's changed in this Virtual DOM, it detects your (Blade-created) elements, sees that it no longer has a use for them, and deletes them.

Now, with that cleared up, [if you look at the Inertia docs's examples, you'll see that they instruct the front-end libraries to mount on the `#app` element](https://inertiajs.com/client-side-setup#initialize-app). As such, the way to fix your direct issue would be change this line:

```js
const app = document.getElementById('app')
```

to something like this:
```js
const app = document.getElementById('page').getElementsByClassName('c-main')[0]
```

Which effectively changes the 'mount point' from your `<div id='app'...` to the nested `<main class='c-main'...`.

---

Now, of course I can end my answer here, but looking at what you're _really trying to do_, is to have a page layout. As such, I'd suggest to [take a look at this instead](https://inertiajs.com/pages#creating-layouts).

Hope it helps! Let me know if you have any other questions.

**Comment by claudiodekker** [comment]
Hi,

Since it's been a while since this question was answered and no follow-up was given, I'm assuming this solved your issue or that it is no longer relevant. As such, I'll be closing this issue. If you feel like it still wasn't answered but you just haven't had the time to reply to it, feel free to re-open the issue at any point by leaving a comment.

Thanks!
