### ISSUE TITLE
Just wondering if InertiaJs can work with Themosis MVC Framework based on laravel illuminate packages

### ISSUE THREAD

**Issue by ThinkDevStudios** [inertiajs/inertia-laravel#123]
Hi Guys. Just wondering if InertiaJs can work with Themosis MVC Framework that is based on Laravel Iluminate packages. What is the process when integrating it with other php libraries.

**Comment by claudiodekker** [comment]
Hi,

I can't say that I'm familiar with the Themosis Framework, but if it uses Illuminate packages, you can always give it a try?

As for implementing it with other php libraries, the process is pretty much non-existent right now, but it's certainly possible, especially since the back-end part isn't that big or complex. The best place to start doing so, would be to dig into how this package works, and to go from there. Here's a good starting point: https://github.com/inertiajs/inertia-laravel/blob/e7b95274dc0f6d4148380e2c45ba1c94f77c1c9c/src/ResponseFactory.php#L52

Of course, do keep in mind that if you decide to create a Thermosis-specific backend adapter, it's not entirely unthinkable that there might be breaking changes in the future, and that it will be (at least for now) entirely up to you to maintain it.

Hope this helps. Good luck!

**Comment by Juhlinus** [comment]
To add on to what @claudiodekker said:

The documentation of [the protocol](https://inertiajs.com/the-protocol) pretty thoroughly explains how to go about writing your own adapter.

**Comment by claudiodekker** [comment]
Hi,

Since it's been a while since this question was answered and no follow-up was given, I'm assuming this answers your question or that it is no longer relevant. As such, I'll be closing this issue. If you feel like it still wasn't answered correctly but you just haven't had the time to reply to it, feel free to re-open the issue at any point by leaving a comment.

Thanks!
