### ISSUE TITLE
View data does not change on navigation

### ISSUE THREAD

**Issue by xavi7th** [inertiajs/inertia-laravel#127]
Excellent package team🥳. I have loved using Inertia and I now use it in all my projects.

I have an issue with view data. 

Per the documentation I have the following code in 2 of my routes

```
public function index()
  {
    return Inertia::render('BasicSite,HomePage')->withViewData([
      'title' => 'Home page title',
      'description' => 'Home page description.',
      'abstract' => 'Home page abstract.',
      'ogDescription' => 'Some description.',
      'twitterDescription' => 'Some description'
    ]);
  }

public function showPrivacyPage()
  {
    return Inertia::render('BasicSite,PrivacyPage')->withViewData([
      'title' => 'Privacy page title',
      'description' => 'Know our privacy policy regarding how we use the information you provide to us.',
      'ogDescription' => 'Know our privacy policy regarding how we use the information you provide to us',
    ]);
  }
```

In the blade file I have the following

```
<title>{{ $title ?? config('app.name')}}</title>
```

However when I navigate between pages, the title and other data does not dynamically change. When I do a full page reload however, it does.

Am I missing something?

Thank you

**Comment by claudiodekker** [comment]
Hi,

On an initial page load, Inertia serves you the entire HTML page, including amongst others the `head` and `body` tags. 

When Inertia makes an XHR visit (using the `<inertia-link>` component, for example), the server detects that it's an Inertia visit, and instead of returning a full HTML response, it returns a JSON response with the JavaScript page component name and data (props). Inertia then dynamically swaps out the previous page component with the new page component, and updates the history state.

Because Inertia (after the initial page load) only controls what's in the Inertia-controlled portion of the body, it doesn't update the title tag, and it stays as it was before like you're describing. As such, we'll need to add some custom javascript logic to update the page details (that are outside of Inertia's "control"). 

One way to do this (assuming you're using [VueJS](https://vuejs.org/)), is to add a piece of custom logic to [one of the lifecycle hooks](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram) of your Page Component:
```js
mounted() {
    document.title = this.title;
}
```

Another way (that I personally prefer), is to use [persistent layouts](https://inertiajs.com/pages#persistent-layouts), and to add a watcher on the `title` prop instead, so that it's automatically updated as the page itself changes without me having to repeat the above logic in every component:
```js
watch: {
    title(newVal) {
        document.title = this.title;
    }
}
```

Alternatively, you can install the [vue-meta](https://github.com/nuxt/vue-meta) package, which will allow you to use 'metadata' on your page components [to achieve the same purpose](https://github.com/inertiajs/pingcrm/blob/617459e6ee82affe6fd2f7981fcc285f95cf4afc/resources/js/Pages/Dashboard/Index.vue) in an (arguably) cleaner way.

Hope it helps! Let me know if you have any questions.

**Comment by reinink** [comment]
@claudiodekker Fantastic answer, thanks for helping out here. 👍
