### ISSUE TITLE
props changed in vue component 

### ISSUE THREAD

**Issue by 19peaches** [inertiajs/inertia-laravel#130]
I'm building a system using Inertia and Laravel and it's flippin awesome, but I have an issue that keeps coming up that I can't resolve.

I'm using the `registerLengthAwarePaginator()` as it is in the Ping demo, and I'm using LaravelSnowflake for creating IDs across my app.

I run my seeder to create organizations and it does a perfect job.

But when I display them, the IDs are not the same as the database IDs. The IDs are all 17 digit numbers generated by Snowflake.

In My Vue component the IDs start off correctly reading from left to right for the first 15 numbers ... but somewhere in Vue or Inertia or somewhere ... the last 2 digits are being rounded to the nearest 10.

For instance:

Actual || Displayed
37648503920529408 || 37648503920529410
37648503945695232 || 37648503945695230

and so on.

The only IDs that render correctly are ones that actually end in 0 ie:

37648503954083840 renders the same.

I've dumped the `LengthAwarePaginator` all the way through the code to the actual response ... and it is correct throughout, so is this a Javascript issue or what is going on?

Any assistance appreciated.

**Comment by claudiodekker** [comment]
This is probably a [floating point issue](https://floating-point-gui.de/errors/rounding/), as it also happens if you directly paste the number in your browser's console:

![Screenshot 2020-08-17 at 19 31 40](https://user-images.githubusercontent.com/1752195/90425588-47226300-e0c0-11ea-92d5-005353d811e6.png)

A simple workaround to this is to cast the values to strings instead, although you'll probably want to do this on your back-end:
![Screenshot 2020-08-17 at 19 32 29](https://user-images.githubusercontent.com/1752195/90425657-64efc800-e0c0-11ea-9dce-19e7d4ff9429.png)

**Comment by 19peaches** [comment]
@claudiodekker 

Thanks so much for your in depth response. I had already switched over to casting these ID's as strings to resolve the issue, but I've also been in contact with kra the Snowflake package owner to see if it's possible to make the integers configurable to produce shorter length ID's usable in Javascript.

To me it makes sense to have these cast properly and transformed into strings.

Thanks again for your help.
