### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by Arafat1243** [inertiajs/inertia-laravel#138]
Hello, everyone!

I create a web site using laravel & inertia-vue. now I want to deploy it on a live server but I can't. can anyone provide me a solution.

**Comment by ishanvyas22** [comment]
What errors are you facing?

**Comment by reinink** [comment]
There is nothing particularly unique on the hosting side of things when it comes to Inertia apps. Simply deploy it as you would a standard Laravel/Vue application. I'd recommend looking into the Laravel documentation.

If you have any particular issues you're facing, feel free to post them here and we'll be happy to help. I am going to close this for now though, since I don't think this an Inertia issue.

**Comment by gilbertoalbino** [comment]
Nice question! 
I think a simple tutorial on some cloud provider like Digital Ocean or Linode would be very helpfull.
I DON'T use Inertia because I can't get it deployed on a Digital Ocean droplet.
I spent 4 months learning this Master Piece and got know idea how to deploy it on production. LoL.

I think most Gods of OpenSource (since they are special species) forget that most people are dummy like me!
