### ISSUE TITLE
Inertia Render can't find view

### ISSUE THREAD

**Issue by arieltoledo** [inertiajs/inertia-laravel#144]
Hi, I just finished the complete Laravel 8 installation using jetstream and inertia. 
I created a folder inside resources/js/Pages/Contacts and inside a vue file called index.vue, in my controller, 

`    public function index()
    {
        $data = Contact::all();
        return Inertia::render('/contacts/index', ['data' => $data]);
    }
    `
But only get a white screen and in the console theres an error 

**[Vue warn]: Error in created hook: "Error: Cannot find module './contacts/index'"**

Seems like Inertia its not looking for the file in the right place ... 
Help will be appreciatte.

**Comment by reinink** [comment]
Hello @arieltoledo, thanks for giving Inertia.js a try!

So, the issue here is that your component name is wrong. Given the path: `resources/js/Pages/Contacts/index.vue`, the component name will be `Contacts/index`, not `/contacts/index`. So like this:

```php
return Inertia::render('Contacts/index', ['data' => $data]);
```

Keep in mind that the component name is case-sensitive, so you'll need to make sure you use the same casing as your Vue component folder and filename. Generally I'd recommend using uppercase filenames for your Vue components (`Index.vue`), as that seems to be the norm.

I hope that helps!

**Comment by maggz69** [comment]
@reinink Are the path separators platform dependent i.e / for unix and \ for windows?

**Comment by reinink** [comment]
@maggz69 I don't know, but I don't think so? I haven't worked on Windows in a long time, but I do know this works on Mac and Linux.

**Comment by ManojKiranA** [comment]
@arieltoledo can you provide a sample repo

**Comment by arieltoledo** [comment]
As @reinink  says was a case-sensitive issue. The folder is named as **Contacts** and the vue file as **Index.vue** so the final code is `return Inertia::render('Contacts/index', ['data' => $data]);`

Now the following wont work  
`return Inertia::render('contacts/index', ['data' => $data]);`
`return Inertia::render('Contacts/Index', ['data' => $data]);`
`return Inertia::render('contacts/Index', ['data' => $data]);`

**Comment by reinink** [comment]
@arieltoledo Glad you got it working! 👍
