### ISSUE TITLE
How can I paginate after return by resource ?

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [inertiajs/inertia-laravel#146]
![inertia](https://user-images.githubusercontent.com/48278861/93024677-e1bb8680-f619-11ea-8557-f6734da6734b.PNG)

I'm new in inertia, 

### Pagination.vue

         <template>
            <nav aria-label="...">
              <ul class="pagination justify-content-center">
                <li class="page-item" :class="{ disabled: pagination.current_page <= 1 }">
                  <a class="page-link" @click.prevent="changePage(1)"  >First</a>
               </li>
                <li class="page-item" :class="{ disabled: pagination.current_page <= 1 }">
                  <a class="page-link" @click.prevent="changePage(pagination.current_page - 1)">👈</a>
               </li>

               <li class="page-item" v-for="page in pages"  :key="page" :class="isCurrentPage(page) ? 'active' : ''">
                <a class="page-link" @click.prevent="changePage(page)">{{ page }}
                    <span v-if="isCurrentPage(page)" class="sr-only">(current)</span>
                </a>
               </li>

               <li class="page-item" :class="{ disabled: pagination.current_page >= pagination.last_page }">
                <a class="page-link" @click.prevent="changePage(pagination.current_page + 1)">👉</a>
               </li>
                <li class="page-item" :class="{ disabled: pagination.current_page >= pagination.last_page }">
                <a class="page-link" @click.prevent="changePage(pagination.last_page)">Last</a>

               </li>
            </ul>
         </nav>
       </template>

     <script>
         export default {
                 props:['pagination', 'offset'],

                methods: {
                   isCurrentPage(page){
                   return this.pagination.current_page === page;
               },
               changePage(page) {
               if (page > this.pagination.last_page) {
                page = this.pagination.last_page;
            }
               this.pagination.current_page = page;
               this.$emit('paginate');
          }
      },
      computed: {
          pages() {
            let pages = [];

            let from = this.pagination.current_page - Math.floor(this.offset / 2);

            if (from < 1) {
                from = 1;
            }

            let to = from + this.offset -1;

            if (to > this.pagination.last_page) {
                to = this.pagination.last_page
            }

            while (from <= to) {
                pages.push(from);
                from++;
            }

              return pages;
             }
           }
          }
       </script>

In vue this pagination works fine but when I implement this in inertia + vue this doesn't work,

I searched a lot but don't find anything on that,

**Comment by reinink** [comment]
Hello @ShekhSaifuddin007, thanks for giving Inertia.js a try.

So, I think the issue here is that you're looking for `pagination` and `offset` as top-level props. Rather, they would be included within the `users` prop. I'd recommend inspecting the `users` prop to see what keys you need. Just like in a classic Vue.js app with an API, you get data back from the server, and that data includes some extra meta information that includes pagination details. That's built into the Laravel paginator.

That said, I personally found it a pain to create the links client-side, so in the Ping CRM demo app I created a modified versions of the length-aware paginator that automatically returns the "windowed" links. You can find that [here](https://github.com/inertiajs/pingcrm/blob/master/app/Providers/AppServiceProvider.php#L73-L143).

And, good news, I worked with Taylor Otwell recently to get this added to the next release of Laravel 8. You can find his announcement tweet about that [here](https://twitter.com/taylorotwell/status/1303752820500434945).

Hope that helps! 🤟

**Comment by ShekhSaifuddin007** [comment]
Wow This great and welcoming....💙💙
