### ISSUE TITLE
How to send data back after processing POST request?

### ISSUE THREAD

**Issue by MHassanSaqib** [inertiajs/inertia-laravel#163]
Hello guys,

I have a scenario where I have to make a post request and fetch and display data back. Referring below image.

![image](https://user-images.githubusercontent.com/7033816/95789448-fc574d00-0cf6-11eb-8723-456a4256ca60.png)

I am a little confused, how this can be accomplished. Please check my code below and correct me. 

```
    public function fetchInformation(Request $request)
    {
        $offer = Claim::fetchOfferByCode($request->code);
        return back()->withOffer($offer);
        // or        return redirect()->route('process.claim.page', compact('offer'));
    }
```

Isn't it the way of passing data to Inertia Pages with Post Request? Please correct me.

**Comment by reinink** [comment]
So, you have two choices in these situations:

# Plain xhr/fetch

Simply make a plain xhr/fetch request to get this data, instead of making an Inertia request. With this setup you simply return plain JSON from your control and handle the response client-side.

## Make an Inertia request

The other option is to make an actual Inertia request. Keep in mind, however, that all Inertia requests must return an Inertia response (a page component with props)...not just plain JSON. Meaning, you'll need to update your controller to return the page you're on back, with this new data. Something like this:

```php
public function fetchInformation(Request $request)
{
    return Inertia::render('MyPage', [
        // any other required data....
        'offer' => Claim::fetchOfferByCode($request->code),
    ]);
}
```

Now you'll have `offer` available as a (reactive) prop client-side, and you can display it.

However, for myself, I probably wouldn't create a new endpoint for this. Rather, I'd update my page endpoint to check for this directly. That way you don't need an additional route/controller for this. Something like this:

```php
public function show(Request $request)
{
    return Inertia::render('MyPage', [
        // any other required data....
        'offer' => $request->code ?
            Claim::fetchOfferByCode($request->code)
            : null,
    ]);
}
```

I'd highly recommend reading through [this discussion](https://github.com/inertiajs/inertia/issues/252). This gives a good overview of how Inertia is intended to work.

I hope that helps! 👍
