### ISSUE TITLE
How to access query params?

### ISSUE THREAD

**Issue by wassim** [inertiajs/inertia-laravel#174]
Is there a way to retrieve query params passed to a child component?

I get $route undefined. Also tried with this.$route.

In parent:

```javascript
<inertia-link :href="route('posts.create', { custom_param: myParam })">
    Add new post
</inertia-link>
```

In child:

```javascript
export default {
    props: {
        myParam: $route.query.myParam
    }
}
```

**Edit:** I've found this in docs, but same problem I can't retrieve data.

```javascript
<inertia-link href="/endpoint" method="post" :data="{ foo: bar }">Save</inertia-link>
```

**Comment by reinink** [comment]
So, `$route` and `route` are not properties that Inertia itself makes available, although we have used the [Ziggy](https://github.com/tighten/ziggy) library in the Ping CRM demo for generating URLs, and there we make the this library available [as a mixin](https://github.com/inertiajs/pingcrm/blob/39cd397852ef5176557e48863eefaff8a74bf00f/resources/js/app.js#L8).

Also, I'm not really sure what you mean that you can't access the query params in the child component. Do you mean you are creating a child element/component within the `<inertia-link>` component? Or do you mean that you're trying to access the query string once you visit a page? Because in that case, you can just use `window.location.search` to get these values.

**Comment by wassim** [comment]
Yes, I'm  trying to access the query string once you visit a page. I used `window.location.search` as you suggested. I tough Inertia makes $route available in views.

**Comment by reinink** [comment]
Understood. As noted, `$route` is not a "thing" in Inertia. You can totally use `window.location.search` (and maybe even the [qs](https://www.npmjs.com/package/qs) library to parse). However, I personally don't ever do this, and instead simply passing the query string values from my response to my view, and then access them as props.

For example, if I have a user search endpoint (`/users?search=Jonathan`), I will pass the `search` value as a prop back to my users page to display back on that page. You can see an example of this in the Ping CRM app [here](https://github.com/inertiajs/pingcrm/blob/master/app/Http/Controllers/UsersController.php#L18) and [here](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Index.vue#L80). I prefer this approach, since props are reactive.

Also, if you pass data to an `<inertia-link>` that uses `post` for the method, it's passed down as the body params. If you pass data to an `<inertia-link>` that uses `get` for the method (the default), it's passed down in the query string.

Not totally sure what you mean by this:

> Does it make a data object available on the target view?

But no, Inertia doesn't pass link data directly to some view. Rather, it submits it server-side, and you can then choose to make it available to your page components by passing it as props (response data), as suggested above.

Hope that helps!

**Comment by wassim** [comment]
Thanks @reinink ! That's helps a lot.

My goal was to pass data from view A to view B, knowing that I use `<inertia-link>` to navigate between the 2 views. What would you recommend to use in this case?

Thanks again for your help!

**Comment by reinink** [comment]
Inertia links are always used for making visits. That's it. So, if an Inertia link navigates between two views, then send the data down from the link in the first view, and pass it back in the response as a prop to the second view. 👍

**Comment by wassim** [comment]
@reinink sorry for being dumb but I tried that method and I got undefined.

View A:

```javascript
<inertia-link :href="route('comments.create')" :data="{ post: post.id }">
    Create new comment
</inertia-link>
```

View B: (http://mysite.test/comments/create?post=1)
 
```javascript
export default {
    props: {
        post: String
    },
}
```

**Comment by reinink** [comment]
@wassim Happy to hear 👍

**Comment by santutu** [comment]
HandleInertiaRequests.php

    ```
public function share(Request $request)
    {
        return array_merge(parent::share($request), [
            'ziggy' => function () use ($request) {
                return array_merge((new Ziggy)->toArray(), [
                    'location' => $request->url(),
                    'query'=>$request->query()
                ]);
            },
        ]);
    }
```

utils.ts
```
import {usePage} from "@inertiajs/inertia-vue3";

export function getQuery() {
    return (usePage().props.value.ziggy as any).query;
}
```

can't use window.location.search in ssr. because node server doee not have window variable.

**Comment by FurrukhJamal** [comment]
> HandleInertiaRequests.php
> 
> ```
> public function share(Request $request)
>   {
>       return array_merge(parent::share($request), [
>           'ziggy' => function () use ($request) {
>               return array_merge((new Ziggy)->toArray(), [
>                   'location' => $request->url(),
>                   'query'=>$request->query()
>               ]);
>           },
>       ]);
>   }
> ```
> 
> utils.ts
> 
> ```
> import {usePage} from "@inertiajs/inertia-vue3";
> 
> export function getQuery() {
>     return (usePage().props.value.ziggy as any).query;
> }
> ```
> 
> can't use window.location.search in ssr. because node server doee not have window variable.

This has saved me quite some time, I was thinking about going with the `window.location.search` and then parsing the link for param approach.

**Comment by FakeMan2332** [comment]
just share props with PageProps where it need ?
like
```php
Intertia::render('SearchItemPage', ['itemId' => $itemId])
```

**Comment by yaayes** [comment]
@santutu provides a great helper, here's an updated version for React, where you can specify a key and fallback value

```ts
import { usePage } from "@inertiajs/react";

export function getQuery(key: any = null, fallback: any = null) {
  let query = (usePage().props.ziggy as Record<any, any>).query;
  query = query.length == 0 ? {} : query; // cuz when empty Laravel return an array - can change it in HandleInertiaRequests.php!

  if (key) {
    return query.hasOwnProperty(key) ? query[key] : fallback;
  }

  return query;
}
```

**Comment by OkonoWil** [comment]
To get the query data add  `'query' => $request->query(),` in HandleInertiaRequests

```php

public function share(Request $request): array
    {
        return [
            ...parent::share($request),
            'auth' => [
                'user' => $request->user(),
            ],
            'ziggy' => fn () => [
                ...(new Ziggy)->toArray(),
                'location' => $request->url(),
                'query' => $request->query(),
            ],
        ];
    }
```

**Comment by josephajibodu** [comment]
> just share props with PageProps where it need ? like
> 
> ```
> Intertia::render('SearchItemPage', ['itemId' => $itemId])
> ```

Yeah, keep it simple. This is better overall unless the query parameters are useful on every page of the app and not needed on the backend.

**Comment by pablo-vega-kloeckner-i** [comment]
For Client-Side using **Vue3,** I found this solution.
``` javascript
import { usePage } from "@inertiajs/vue3";
const page = usePage();

const queryParams = computed(() => {
  const url = new URL(page.url, window.location.origin);
  return Object.fromEntries(url.searchParams.entries());
});

```

> 🛑  Only if **SSR** is not enabled.
