### ISSUE TITLE
Laravel Validation errors

### ISSUE THREAD

**Issue by jsandfordhughes** [inertiajs/inertia-laravel#184]
Hi there, 

Most of my app uses modals with forms in to create data,

I am using `$inertia.post` to submit data to the backend, the issue I am seeing is that the default Laravel behaviour when a validation error occurs is to redirect back with a 302 and the errors in the session. 

This works fine and the validation errors get sent through to the front end however inertia sees this as a successful response which it is not. In the `onSuccess` event I need to clean up after a successful response like closing the modal and emptying the form back to blank however if a validation error occurs Intertia triggers the `onSuccess` event. 

To get around this at the moment I have a mixin in vue that checks the Inertia props to see if the errors object is populated within the `onSuccess` event. Is there a better way around this? Can we somehow have Laravel return a failed response but still have Intertia update the shared variables?

Cheers Joe

**Comment by reinink** [comment]
> This works fine and the validation errors get sent through to the front end however inertia sees this as a successful response which it is not.

The way you need to think about this is like a regular full page form submission, server-side rendered application. When you submit a form in that scenario, Laravel redirects you back to the same form page, with the `$errors` available to you in Blade. That is a `200` response, not a `422`. Inertia works the same way. The reason why `onSuccess()` is called is because it *was* a successful page visit.

This often throws off developers new to Inertia, since they're very used to inspecting the response code of an xhr/fetch request. That's not how Inertia works, since a `422` is never generated. The validation fails, and a redirect occurs. And honestly, this behaviour is actually a very good thing. It's what makes working with forms in Inertia so wonderful.

> Is there a better way around this?

No, what you're doing is exactly right. This is what happens in Jetstream, and also in Ping CRM, the Inertia demo app ([see here](https://github.com/inertiajs/pingcrm/blob/39cd397852ef5176557e48863eefaff8a74bf00f/resources/js/Pages/Users/Edit.vue#L87-L97)). Just keep in mind that it's now `this.$page.props.errors` in newer versions if Inertia (we still need to update Ping CRM).

I hope that helps!

**Comment by jsandfordhughes** [comment]
Great, thanks for the quick response!
