### ISSUE TITLE
get the actual data from server using inertia/vuejs

### ISSUE THREAD

**Issue by steven-lury** [inertiajs/inertia-laravel#192]
I'm using `laravel & inertia/vue` and  have a question.vue component which shows the question and it's answers. Initially the answers are empty. I fetch the paginated answers in created hook because I don't want to load all answers related to the question. I don't know how to handle it with inertia.

question.vue

     <template>
         //....do some stuff
         <div class="card-body">
              <div class="card-title">
                  <h5>{{setCountAnswer}}</h5>
              </div>
            <answer v-for="(answer) in answers" :key="answer.id" :answer="answer"></answer>
         </div>
      </template>

        <script>
        import Answer from './Answer';
        export default {

       props: ['question'],
       data() {
           return {
               questionId : this.question.id,
               answers: []
           }
       },
       created () {
           this.fetch(this.$route('questions.answers.index', this.questionId))
       },
       components: {
           Answer
       },
       methods: {
           fetch(url) {
               this.$inertia.get(url, {
                     onSuccess: (res) => {
                      console.log(res)
                 }
              })

          }
       }
      }
      </script>
`
In AnswersController.php

      public function index(Question $question) {
           $answers = $question->answers()->with('user')->simplePaginate(4);
           //how to handle it with inertia
          return response()->json('answers' => $answers);
      }

**Comment by reinink** [comment]
Can you please clean up the code and format it properly?

**Comment by steven-lury** [comment]
@reinink I did it, thanks in advance

**Comment by steven-lury** [comment]
@reinink to explain more, `Answers` component is inside `QuestionShow` component. So when the question is loaded, I want to fetch related answers to the question with pagination. That's why I want to pass only answers without any reload or ...

**Comment by maggz69** [comment]
@steven-lury I believe this is more of a VueJS Question rather than inertia. But I believe this would be one of the best ways to work it out. 

**What I've changed in your code**
1. The name of the function fetch. This might conflict with the `fetch` [api used across browsers](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
2. Rather than created, I've used mounted as this means the data will be available faster since created hook waits for the DOM to be rendered while mounted hook is called without the dom having to be ready.

**Pagination**
From your code, you're using simplePaginate, this will return an Paginator object which resembles the following in json

```
{
    'current_page':2,
    'data':[
        {
            'id':16,
            'answer':'Kenya is my country'
        },
    ]
    'first_page_url':"http://localhost/question/1/answers?page=1",
    'next_page_url':"http://localhost/question/1/answers?page=3",
    'prev_page_url':"http://localhost/question/1/answers?page=1",
    'per_page':":15"
}
```

As you'd like to paginate these answers rather than load them all at once, you need to handle pagination in the FrontEnd. This is preferable through the `next_page_url` and `prev_page_url` attributes. 

**Data Objects**

This is how I would have stored the data objects to handle pagination as well. 

```
return {
    questionId : this.question.id,
    answers: [],
    answersPagination:{
        next_page:"",
        prev_page:""
     }
}
```

**Full Code**
```
<template>
    <div class="card-body">
        <div class="card-title">
            <h5>{{setCountAnswer}}</h5>
        </div>
        <answer v-for="(answer) in answers" :key="answer.id" :answer="answer"></answer>
        <button @click="fetchNextPageAnswers">Go To Next Answers</button>
        <button @click="fetchPreviousPageAnswers">Go To Previous Answers</button>
    </div>
</template>

<script>
    import Answer from './Answer';
    export default {
        props: ['question'],
        data() {
            return {
                questionId : this.question.id,
                answers: [],
                answersPagination:{
                    next_page:"",
                    prev_page:""
                }
            }
        },
        mounted () {
            this.fetchAnswers(this.$route('questions.answers.index', this.questionId))
        },
        components: {
            Answer
        },
        methods: {
            fetchAnswers(url) {
                this.$inertia.get(url, {
                    onSuccess: (res) => {
                        this.answers = res.answers.data;
                        this.answersPagination.next_page = res.answers.next_page_url;
                        this.answersPagination.prev_page = res.answers.prev_page_url;
                    }
                })
            },
            fetchNextPageAnswers(){
                this.fetchAnswers(this.answersPagination.next_page);
            },
            fetchPreviousPageAnswers(){
                this.fetchAnswers(this.answersPagination.prev_page);
            }
        }
    }
</script>
```

![inertia laravel pagination](https://user-images.githubusercontent.com/20341115/100711464-fb1ed400-33b9-11eb-9097-4a454e9399ed.png)

**Comment by steven-lury** [comment]
@maggz69 Hi, first of all I'd like to thank for your answer. You know, my problem is how to pass raw data from `laravel/inertia`. As I mentioned, in `AnswersController.php` if I have sth like this ` return response()->json(['answers' => $answers])`, It shows me a json in DOM.
To explain more, I want to fetch paginated answers inside `Answers.vue`

    `AnswersController.php`
     public function indext(Question $question) {
          $paginatedAnswers = $question->answers()->simplePaginate(3);
          //if I return in this way, I'll get json response instead of array
          return response()->json(['answers' => $paginatedAnswers])
         // what I want is how I can return paginatedAnswers in `created ` or `mounted` hook
      }
**Note!** Answers component is inside Question component.

**Comment by maggz69** [comment]
Look like inertia renders the response rather than actions it on a callback. Have you tried using the the fetch api / axios instead?

**Comment by steven-lury** [comment]
@maggz69 using axios works, but I'm wondering if there is any solution with `inertia`. Thanks in advance

**Comment by maggz69** [comment]
> @maggz69 using axios works, but I'm wondering if there is any solution with `inertia`. Thanks in advance

@steven-lury 
So ideally you shouldn't use inertia requests for non inertia responses. This is mentioned [here](https://github.com/inertiajs/inertia/issues/90#issuecomment-550311176)

**Comment by reinink** [comment]
So, I think the issue here is your controller. You cannot return a plain JSON response to Inertia. All Inertia requests *must* receive an Inertia response. So, I'd recommend updating your controller to something like this:

```php
public function index(Question $question) {
    return Inertia::render('Question', [
        'answers' => $question->answers()->with('user')->simplePaginate(4);
    ]);
} 
```

Any data to pass to the `Inertia::render()` function will be available in your `Question` component.

Keep in mind, however, that pagination can be a little tricky in Laravel, since the paginator will return a `toArray()` version of all your models, which is maybe more data than you want. I [submitted an updated to Laravel 8.x](https://github.com/laravel/framework/pull/34657) that allows you to call `through()` on the paginated data to modify it. For example:

```php
public function index(Question $question) {
    return Inertia::render('Question', [
        'answers' => $question->answers()->with('user')->simplePaginate(4)->through(function ($answer) {
            return [
                'id' => $answer->id,
                'whatever' => $contact->whatever,
            ];
        }),
    ]);
} 
```

I hope that helps! 👍
