### ISSUE TITLE
Inertia/Laravel-App in Subfolder

### ISSUE THREAD

**Issue by serumk** [inertiajs/inertia-laravel#196]
I have a Inertia/Laravel-app running in a subfolder (https://localhost/toc). Everything works well so far, Ziggy-Routing is adding /toc to the links perfectly, but in the Inertia page-object the url-property is missing the base folder (so it says /changes instead of /toc/changes). Using the navigation in the app works also, but the URL in the browser bar is set by Inertia to display the URL without the base folder.

In the Inertia\Response the page-object is built with 'url' => $request->getRequestUri() - where the RequestUri doesn't contain the folder (which makes sense from the Lavarel-Framework point of view). Is there a recommended solution for this?

Adding a config-option for a subfolder like so
'url' => config('inertia.subfolder') . $request->getRequestUri() 
in the Inertia\Response would solve the issue, but I see no way injecting my response into the ResponseFactory.

Any suggestions?

**Comment by claudiodekker** [comment]
Hi @serumk,

Since Inertia uses Laravel's state as it's own, the recommended solution here is to modify it's settings/environment in such a way that it generates the URL properly. One easy way to do this is to use a custom Middleware.
Something like this (untested) should do the trick:

```php
<?php

namespace App\Http\Middleware;

use Closure;

class RewriteRequestUri
{
    public function handle($request, Closure $next)
    {
        $request->server->set('REQUEST_URI', $_SERVER['REQUEST_URI'] . 'toc/');

        return $next($request);
    }
```

In case that's not an option, another thing you could do with Ziggy is to set the base URL. 
I believe that something along these lines should work:

```js
    var Ziggy = {
        namedRoutes: {/* ... */},
        baseUrl: 'http://demo.inertiajs.com/',
        baseProtocol: 'http',
        baseDomain: 'demo.inertiajs.com',
        basePort: false,
        defaultParameters: []
    };
```

Hope this helps!
