### ISSUE TITLE
Accessing data in root template + inertia_vue issue!!

### ISSUE THREAD

**Issue by mostafa6765** [inertiajs/inertia-laravel#20]
# laravel router 

```php 
Route::get('/contact', function () {
  Khead::setTitle('acontact');
  $event = "ok this is event";
  return Inertia::render('Contact', ['eventi' => $event])
                ->with(['meta_description' => $event]);
});
```
# inertia vue 

```vue 
<inertia-link href="/contact">contact</inertia-link>
```

`when I click contact route that time return an error` 

```bash 
BadMethodCallException
Method Illuminate\Http\JsonResponse::with does not exist.
```

`but normal anchor tag works properly.`

**Comment by MichaelDeBoey** [comment]
@mostafa6765 Do you have a reproduction repo to checkout please? 🤔

**Comment by reinink** [comment]
Yeah, I don't think we have enough to go on here. If you could reproduce this and share it as a repo, that would great.

**Comment by mostafa6765** [comment]
* [github rep](https://github.com/mostafa6765/inertiavl-project-issue)
* [production on heroku](https://inertia-issue.herokuapp.com/about) 

inertia link return error. @reinink , @MichaelDeBoey

**Comment by reinink** [comment]
Ahh yes, this makes perfect sense. 🤦🏻‍♂️

Chaining the `->with()` method works when it's a view response (full page load), but obviously won't work on Inertia responses, since those return a JSON response, not a view response.

I think this only solution is to update the `Inertia::render()` function to take a second set of optional template variables.

Leave this with me.
