### ISSUE TITLE
On form post/patch submission, returning back to the submission page clears all the fields

### ISSUE THREAD

**Issue by mattmultiplied** [inertiajs/inertia-laravel#201]
On a form post submission, returning back to the previous page clears the fields although the props in Vue do contain the correct data. I have tried both `resetOnSuccess: false` and `preserveState: false` but on redirecting back the updated data isn't there.

I've also tried calling the show controller method with the key passed through although all the fields still get cleared on redirecting back the page of the form submission.

Controller Update Method
```
$this->validate($request, [
            'full_name' => 'required|string',
            'company' => 'required|string',
            'phone_number' => 'required|string',
            'email_address' => 'required|email',
        ]);

        $installer->update([
            'full_name' => $request->full_name,
            'company' => $request->company,
            'phone_number' => $request->phone_number,
            'email_address' => $request->email_address,
        ]);

return redirect()->back();

```
Submission Method
```
submit() {
    this.form.post(route('installer.update', this.installer.id), this.form, {
        preserveScroll: true
    }, {
        resetOnSuccess: false
    }, {
        preserveState: false
    })
},
```

**Comment by reinink** [comment]
Hey Matt,

I don't think this is an issue related to this adapter (`inertia-laravel`), but rather an issue with Jetstream. There are some known issues with Jetstream 1.x and Inertia. Fortunately, those issues have been resolved for the upcoming Jetstream 2.x release.

That said, I think the issue here is that you're putting the `resetOnSuccess` property in the `this.form.post()` arguments. Instead, this needs to go in the `this.$inertia.form` arguments. Here's an example form the docs:

```js
data() {
    return {
        form: this.$inertia.form({
            name: this.name,
            email: this.email,
        }, {
            bag: 'updateProfileInformation',
            resetOnSuccess: true,
        }),
    }
}
```

I hope that helps!

**Comment by mattmultiplied** [comment]
Thanks Jonathan, sticking the `resetOnSuccess: true` in the correct place has actually solved my issue!

**Comment by reinink** [comment]
Awesome! 👏 

FYI, `resetOnSuccess` is gone in Jetstream V2. 👍
