### ISSUE TITLE
Please Help me , You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### ISSUE THREAD

**Issue by fikrisuheri** [inertiajs/inertia-laravel#207]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by fikrisuheri** [comment]
![image](https://user-images.githubusercontent.com/61069138/104144783-4b487780-53f7-11eb-868e-93404c096198.png)

**Comment by RobertBoes** [comment]
Since you placed this issue at the Laravel adapter, I assume you're using Laravel mix v6. A quick search with the error + laravel mix led me to this issue/solution https://github.com/JeffreyWay/laravel-mix/issues/2625#issuecomment-733842722
So all you need to do is replace `.js()` with `.vue() / .vue({ version: 2 })` in your `webpack.mix.js` file.

**Comment by reinink** [comment]
Thanks for your help here @RobertBoes. That looks correct.

**Comment by patrikkaprinay** [comment]
This didn't solve the issue for me, but this did:
app.js
`require('./bootstrap');

import App from './vue/App.vue';
import { createApp } from 'vue'

const app = createApp(App).mount('#app');
`

**Comment by flutterq2** [comment]
[[Solved] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file in vueJs](https://exerror.com/you-may-need-an-appropriate-loader-to-handle-this-file-type-currently-no-loaders-are-configured-to-process-this-file-in-vuejs/)
