### ISSUE TITLE
PHPUnit::assertSame vs. PHPUnit::assertEquals

### ISSUE THREAD

**Issue by jago86** [inertiajs/inertia-laravel#224]
@claudiodekker 

In some cases, like when I'm working with in memory sqlite3 databases for testing, some values are returned as strings, but of course in my test method I write the expected value as an integer. For example: 

```php
$response->assertInertia(fn ($page) => $page
            ->component('Jobs/Index')
            ->has('jobs.data', 1, fn ($page) => $page
                ->where('not_hired_people_count', 2)
                ->etc()
            )
        );
```

In my particular context the test fails, but just because the type of data. The message says:

```sh
Inertia property [jobs.data.0.not_hired_people_count] does not match the expected value.
Failed asserting that '2' is identical to 2.
``` 
I figured out that the failure is because the where method uses under the hood **PHPUnit::assertSame**.

I honestly don't now why that count value is set as a string by Eloquent, but in any case, in the the majority of cases, I use **assertEquals** instead **assertSame** in my tests. I know that one solution is just wrap my number in quotes, but I'm just wondering, why don't use **assertEquals** instead of **assertSame** to bring a little more flexibility? There is some reason that makes **assertSame** a better option?

Saludos 🤓

**Comment by claudiodekker** [comment]
Hi,

The problem with `assertEquals` is it 'loosely' matches values, meaning that (for example) an integer value of `1` also 'equals' a boolean value `true`, and from a testing library's perspective [we don't want this to happen](https://github.com/inertiajs/inertia-laravel/blob/097fe5b3be73ab8edea1a5216a696f627c1f6b03/tests/Testing/AssertTest.php#L555-L570), because it would/could lead to a lot of false positives, which in turn makes for unreliable tests.

While I recognize that this causes problems with in-memory sqlite database, _in reality_ it's instead the in-memory sqlite database + Eloquent combination that's causing these issues. And as much as I _used to love_ testing against those kinds of databases (they're _perfect_ in CI-pipelines!), this is unfortunately just one of their limitations, and 'fixing' our library to make it work would actually just make things worse for everyone else.

Instead, I highly recommend to just test against a 'real' database server that matches your production environment (e.g. MySQL, Postgres), and to use the `RefreshDatabase` trait while doing so.

### Using a real database server in your tests
If you decide to go down this path, don't forget to create a separate _database_ for testing instead of re-using the one that your app uses on the dev. environment, otherwise you run the risk of running into endless issues/conflicts when interacting with the database manually (e.g. by using your app in the browser and creating, updating or deleting a thing). The easiest way to configure this is to re-use the `.env` credentials for the 'default' connection, but to just override the `DB_DATABASE` parameter in your `phpunit.xml` variables.

Finally, if you happen to test against a Github Actions database, you can fairly easily configure a 'real' database server through the '[services](https://docs.github.com/en/actions/guides/about-service-containers)' option:
```yml
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      ... (your steps)

    
    services:
      postgres:
        image: 'postgres:10-alpine'
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: laravel 
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
```

Hope this helps!

**Comment by jago86** [comment]
Yeah, you're right. For now, I'm just assuming that with SQLite I'll get some string values. Thanks for answer and sorry for the late.
