### ISSUE TITLE
Testing, Inertia page component file not exists after update to ^0.4.0

### ISSUE THREAD

**Issue by samueledirito** [inertiajs/inertia-laravel#229]
Hello,
before upgrading to new 0.4.0 package, using claudiodekker inertia-laravel-testing package, everything was fine and all my tests pass.
After upgrading, my TestCase is not able to find any Inertia component.
Is there something that should be added to test code?

TIA

**Comment by samueledirito** [comment]
My fault, something is wrong with page. I missed to restart server after upgrade... what a loser :D

**Comment by samueledirito** [comment]
OK, i fix all errors and app navigates correctly.
My tests cannot find any component yet.

I'm using React, Laravel 8 and my components are nested in default path resources/js/Pages
![image](https://user-images.githubusercontent.com/3239563/110754067-a8ba4280-8247-11eb-961e-46673f605899.png)

**Comment by herpaderpaldent** [comment]
Ok so i had a similiar issue with package development: https://github.com/claudiodekker/inertia-laravel-testing/issues/33 

Maybe it is worth to dump the `$page` and check the path where the helper is seeking the component. 

Please note the referred issue has another config-key as the final inertia one:

```
//Setup Inertia for package development
        config()->set('inertia.testing.page_paths', array_merge(
            config()->get('inertia.testing.page_paths', []),
            [realpath(__DIR__ . '/../src/resources/js/Pages'), realpath(__DIR__ . '/../src/resources/js/Shared')],
        ));
 ```

**Comment by reinink** [comment]
So, the config file changed slightly for defining your page locations. Update your `/config/inertia.php` file to match the new config: https://github.com/inertiajs/inertia-laravel/blob/master/config/inertia.php

That should take care of it. 👍

**Comment by herpaderpaldent** [comment]
possible you need to edit the config regarding file endings too?

**Comment by herpaderpaldent** [comment]
@claudiodekker within @samueledirito 's screenshot i noticed the pages file endings `.jsx`. However, within the inertia config file i fail to see that particular file ending:
https://github.com/inertiajs/inertia-laravel/blob/097fe5b3be73ab8edea1a5216a696f627c1f6b03/config/inertia.php#L27-L34 hence together with my suggestion on how to config this file via the ServiceProvider i wanted to highlight the fact that the config might need to be extended to support his use case.

**Comment by robsontenorio** [comment]
@claudiodekker just noticed a problem, because file path is case sensitive in linux.

https://github.com/inertiajs/inertia-laravel/blob/master/config/inertia.php#L23

<img width="430" alt="image" src="https://user-images.githubusercontent.com/118955/126848577-2d9f485e-ed2d-4e4f-ad72-d794ba627201.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/118955/126848633-ac76c95f-b711-4d84-acc1-6d4d562d0380.png">



On my local Mac it passes, but not in Gitlab pipeline (linux).

**Comment by claudiodekker** [comment]
Yeah, that's expected. Paths are supposed to be case sensitive, otherwise you start running into many many different issues (even with git merge conflicts etc.)

In either case, to fix this, you can publish the configuration file of the package (php artisan vendor:publish --provider="Inertia\ServiceProvider") and modify the search paths in config/inertia.php to reflect the lowercase folders.
