### ISSUE TITLE
[Feature request]: Allow unordered response json fragments

### ISSUE THREAD

**Issue by eithed** [inertiajs/inertia-laravel#234]
Consider a response where a certain json fragment is always at certain level of the tree, but can change order ie

```
{
   data: {
      fields: [{ id: 'foo'}, { id: 'bar'}]
   }
}
```

and

```
{
   data: {
      fields: [{id: 'bar'}, { id: 'foo'}]
   }
}
```

For such responses one cannot easily write assertions, as:

```
$response->assertJson(function (AssertableJson $json) {
   $json->has('data.fields', function (AssertableJson $json) {
      $json->where('id', 'foo');
   }
}
```

will check for existence of `data.fields.id`

and

```
$response->assertJson(function (AssertableJson $json) {
   $json->has('data.fields.0', function (AssertableJson $json) {
      $json->where('id', 'foo');
   }
}
```

will fail when the fragments change order.

One could write such test as:

```
$response->assertJson(function (AssertableJson $json) {
   $json->where('data.fields', function($field) {
      return $field->pluck('id')->contains('foo');
   }
}
```

I think it's an ugly workaround, and I'd personally prefer to use AssertableJson so that I can filter the children further (ie. I want test to pass if a field exists where id is foo and it has options where one of options is bar)

I don't know if currently such functionality exists, but would appreciate either support of Laravel * notation, ie:

```
$response->assertJson(function (AssertableJson $json) {
   $json->has('data.fields.*', function (AssertableJson $json) {
      $json->where('id', 'foo');
   }
}
```

or introduce a `hasAny` method that will explicitly iterate through array type fragment and match any element that fulfils the assertion ie:

```
$response->assertJson(function (AssertableJson $json) {
   $json->hasAny('data.fields', function (AssertableJson $json) {
      $json->where('id', 'foo');
   }
}
```

**Comment by claudiodekker** [comment]
Hey @eithed,

Due to the nature of test output being predictable by design, situations in which a 'random order' is caused on purpose (e.g. a raffle) should in general be very limited, and while the callback-based assertions aren't "great", you can still create your own alias method as the Assertions are [Macroable](https://tighten.co/blog/the-magic-of-laravel-macros/).

In either case, we're [deprecating the Assertions in favor of Laravel's AssertableJson](https://github.com/inertiajs/inertia-laravel/pull/338), so we won't be implementing this. 

In either case, thank you for your feature request and interest in Inertia! :)
