### ISSUE TITLE
Two blade layouts using two different javascript framework [not working]

### ISSUE THREAD

**Issue by jovvybersamin** [inertiajs/inertia-laravel#238]
- I have a Control Panel blade file located in resources/views/cp/app.blade.php
- And a FrontEnd blade file located on resources/frontend/app.blade.php
- cp.js using React framework for CP Layout
- app.js using Vue Framework for frontend Layout

On my HandleIntertiaRequest.php I have this code.

```php
    // Set root template via method
    public function rootView(Request $request)
    {
        if ($request->is('cp/*')) {
            return 'cp.app';
        } else {
            return 'frontend.app';
        }
    }
````

This middleware works perfectly fine if you only loaded the correct 'app.blade.php' layout.

This is what happened.

On my Login View its using the VueJS Javascript files and using resources/frontend/app.blade.php

Upon successfull Login, The user will be redirected to /cp/dashboard.

And what I'm expecting to see is the ReactJS files to be loaded or the resources/cp/app.blade.php should be loaded.

But that's not the case since intertiaJS handles the routing client side, it didn't load the correct 'app.blade.php' even though the url path is "cp\*" but refreshing the page loads the correct 'app.blade.php' because the HandleIntertiaRequest middleware takes care of it.

Now, how I will tell IntertiaJS that it should load the correct 'app.blade.php' after Login?

**Comment by claudiodekker** [comment]
Hi,

So, because Inertia is a Single Page Application, it [only uses Blade to send some basic html, as well as the required javascript/css to render itself in the client's browser](https://github.com/inertiajs/pingcrm/blob/master/resources/views/app.blade.php). Every Inertia request after that (submitting a form, clicking a link, etc..) doesn't ever use blade again, by design.

Instead, what you'll want to do, is to move your `frontend` and `cp` layouts into two [Persistent Layouts](https://inertiajs.com/pages#persistent-layouts) Vue components, and then just use those on the pages where it's relevant. You can think of it as Inertia's version of Blade's `@extends(layout)`.

Hope this helps!

**Comment by takielias** [comment]
> 

Hi, I have also followed this technique. But could not make it. Is there anyway to do full page reload after login?

**Comment by takielias** [comment]
> Hi,
> 
> So, because Inertia is a Single Page Application, it [only uses Blade to send generic/basic html, as well as the required javascript/css to render itself in the client's browser](https://github.com/inertiajs/pingcrm/blob/master/resources/views/app.blade.php). Every Inertia request after that (submitting a form, clicking a link, etc..) doesn't ever use blade again, by design.
> 
> Instead, what you'll want to do, is to move the style-specific parts of your `frontend` and `cp` layouts into two [Persistent Layouts](https://inertiajs.com/pages#persistent-layouts) Vue components, and then just use those on the pages where it's relevant. You can think of it as Inertia's version of Blade's `@extends(layout)`.
> 
> Hope this helps!

Hi, I have also followed this technique. But could not make it. Is there anyway to do full page reload after login?
