### ISSUE TITLE
In My Project Inspect Elements For me getting  jetstream="[object Object]"  ..

### ISSUE THREAD

**Issue by Vigneshonemodo** [inertiajs/inertia-laravel#256]
![WhatsApp Image 2021-04-17 at 10 37 55 AM](https://user-images.githubusercontent.com/58412449/115102522-063d5f80-9f69-11eb-819a-30b5b809f5e8.jpeg)
Hi There ... 
    Above i attach image i mark some error .. Like ( jetstream="[object Object]" )  For me Getting like this Please Help me how to solve that error ... Please help me anyone .. am waiting for your message ... 

by 
 Vignesh R

**Comment by tnorthcutt** [comment]
I don't know if this is helpful, but this looks very similar to this pair of bugs in Laravel Mix and vue-loader:

https://github.com/JeffreyWay/laravel-mix/issues/2756
https://github.com/vuejs/vue-loader/issues/1612

No idea if it's related but maybe that helps you look in the right direction.

**Comment by claudiodekker** [comment]
Hey 👋,

I'm going to close this issue, because I believe it's already answered by @tnorthcutt, and furthermore doesn't appear to be related to a bug or feature with the Inertia library itself (Jetstream is not Inertia, but rather a separate library that uses Inertia).

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!
