### ISSUE TITLE
Laravel & Inertia.js – reactivity problem (vue3)

### ISSUE THREAD

**Issue by arulananth** [inertiajs/inertia-laravel#271]
could it be that Inertia.js page components are blocking the reactivity of vue?

I have a Page component, in this component is a normal single file component.

I have a function that adds items to the ItemsManager.items object.
When I’m running this function the single component below doesnt adds this items in the v-for.
But when I’m reload the Page Component it works and the previously added items appear.

**Component**
<template>
    <div>
        <div v-for="item in items" :key="item.$key">
            test
        </div>
    </div>
</template>

<script>
import { ItemsManager } from "./utils.js";

export default {
    name: "test-component",
    data: () => ({
        items: ItemsManager.items
    }),
};
</script>

**utils.js:**

export const ItemsManager = {
    items: [],
    add(item) {
        item.$key = this.items.length;
        this.items.unshift(item);
    },
};

**function that adds the items (in page component):**

addItem(title, options) {
    ItemsManager.add({
        name: title,
        options: options
    });
},

**Comment by arulananth** [comment]
@bonzai  @crynobone

**Comment by claudiodekker** [comment]
Hey 👋,

I'm assuming this is already by far an issue that's no longer relevant at this point, but to answer your question: 
No, Inertia shouldn't and doesn't block reactivity. Your code also doesn't seem like it does to me.

Are you sure there's no third-party plugin/JS library that simply doesn't play well with lots of items or dynamically updated DOM elements?

In either case, since this has been open for a while and doesn't really seem to be an Inertia-related bug, I'm going to close this issue for now. If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!
