### ISSUE TITLE
API Resource pagination in closures missing metadata

### ISSUE THREAD

**Issue by gilbitron** [inertiajs/inertia-laravel#298]
When using pagination with an API Resource inside a closure, the pagination object is missing the metadata. This seems to be a similar issue to #28 but happens specifically when using closures for partial reloads. For example:

```php
return Inertia::render('App/Users', [
    'table' => function () {
        $users = User::paginate(20);

        return [
            'users' => UserResource::collection($users),
        ];
    }
]);
```

If I don't use a closure or if I don't use the API resource class, the full paginated object (including metadata) is returned in the response.

**Comment by NickSdot** [comment]
Hi. I was able to reproduce this. 

### Case 1

Not working. ❌ Your case.

```php
return Inertia::render('App/Users', [
    '1test' => function () {
        return [
            'users' => UserResource::collection(User::paginate(5)),
        ];
    },
]);
```
<img width="302" alt="image" src="https://user-images.githubusercontent.com/32384907/147901788-18d30180-29df-4122-977c-6afdab31f778.png">

### Case 2

Is working. ✅ This is the same approach as in the [shared data docs](https://inertiajs.com/shared-data).

```php
return Inertia::render('App/Users', [
    '1test' => [
        'users' => function () {
            return UserResource::collection(User::paginate(5));
        }
    ],
]);

```
<img width="249" alt="image" src="https://user-images.githubusercontent.com/32384907/147901946-0de7a143-c7df-4cf8-9ffc-9c130aefabbd.png">

### Case 3

Is working. ✅ Standard approach.

```php
return Inertia::render('App/Users', [
    '1test' => function () {
        return UserResource::collection(User::paginate(5));
    },
]);
```
<img width="205" alt="image" src="https://user-images.githubusercontent.com/32384907/147902017-4b250786-1ce4-4813-8fc3-6b269f91bb01.png">

---

@claudiodekker I assume that this is not is an intended behavior? I'll send a PR now and mark it is draft, because I didn't add any new tests. Old still pass. In case it is mergable I am happy to add extra tests fior it.

@gilbitron if you want please test the following PR and let me know if this solves your issue.

**Comment by claudiodekker** [comment]
@NickSdot Thanks for the detailed reproduction :)

**Comment by NickSdot** [comment]
> @NickSdot Thanks for the detailed reproduction 👍

@claudiodekker added test and changes as requested. Ready for review.
