### ISSUE TITLE
Laravel Passport authorization flow not working with Inertia?

### ISSUE THREAD

**Issue by abbluiz** [inertiajs/inertia-laravel#303]
When Laravel Passport redirects back to an external URI after the OAuth 2.0 authorization flow, it renders an iframe of the external website, instead of actually redirecting to the external website.

**Comment by abbluiz** [comment]
The thing is I could use `Inertia::location($url)` to redirect to the external client URL, but this is internal of Passport. The workaround I found was to override the handle method in `HandleInertiaRequests.php`:

```php
    public function handle(Request $request, Closure $next)
    {
        $parentResponse = parent::handle($request, $next);

        if (!empty($request->redirect_uri)) {
            return Inertia::location($parentResponse->headers->all()['location'][0]);
        }

        return $parentResponse;
    }
```

**Comment by abbluiz** [comment]
I have updated my middleware. It is easier to understand now:
```php
public function handle(Request $request, Closure $next)
{
    $parentResponse = parent::handle($request, $next);

    $location = $parentResponse->headers->get('Location');

    if ($this->isExternal($location)) {
        if (request()->inertia()) {
            return inertia()->location($location);
        }

        return redirect()->to($location);
    }

    return $parentResponse;
}
```
A method to check if an URL is external, which is used above:
```php
public function isExternal($url)
{
    $internalHost = parse_url(config('app.url'), PHP_URL_HOST);
    $internalPort = parse_url(config('app.url'), PHP_URL_PORT);

    $host = parse_url($url, PHP_URL_HOST);
    $port = parse_url($url, PHP_URL_PORT);

    return $host !== $internalHost || $port !== $internalPort;
}
```

**Comment by claudiodekker** [comment]
Hey @abbluiz, thanks for reporting this issue.

Whether Inertia is compatible with Passport or any third-party library really depends on the third-party library for the most part, as Inertia in and by itself is just a generic library without. However, I'll leave this issue open so that we can investigate and perhaps come up with a fix for this specific to Passport later.

My personal approach to this would probably be to add a special route that uses `Inertia::location()` to redirect to the Passport OAuth route. That way, you immediately (as the first step in the chain) tell Inertia that we're no longer using Inertia going forward, allowing Passport to properly render it's routes/do it's thing. Then afterwards, you can make sure it redirects back to your Inertia pages.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.

**Comment by JGamboa** [comment]
what was the fix? im geting the same problem an iframe
