### ISSUE TITLE
302 instead of 303 after DELETE request?

### ISSUE THREAD

**Issue by mathiasselleslach** [inertiajs/inertia-laravel#335]
Hi Guys,

First of all, many many many (...) thanks for Inertia! ❤️ 
It's amazing how easy this all is, and how smooth this all works!

Today I noticed that after a Delete request I was getting the exact behavior as described here on the Rails repo: https://github.com/inertiajs/inertia-rails/issues/58

Ps: I have the Inertia Middleware installed as it should, and am on the latest version or inertia-laravel.

This does not work:

```
return Redirect::route('admin.my-route');
```

This works like a charm:

```
return Redirect::route('admin.my-route')->setStatusCode(303);
```

**Comment by RobertBoes** [comment]
> If you're using one of our official server-side adapters, redirects will automatically be converted.
> https://inertiajs.com/redirects#303-response-code

I think the middleware might not be applied on that route, because this does the conversion automatically when an Inertia request is made: https://github.com/inertiajs/inertia-laravel/blob/b0fd3abeb531c883486ec5d75a591a118ca7e83c/src/Middleware.php#L127-L132
And I don't see anything obvious that would suggest why it wouldn't work

**Comment by mathiasselleslach** [comment]
Im sorry, im an idiot...

After a good night sleep, this morning I realized I wrote a regular axios request 🤦 
So naturally the X-Inertia header is missing...

Sorry to both you guys

Closing.
