### ISSUE TITLE
Redirect aren't 303 in v0.5.1

### ISSUE THREAD

**Issue by grantholle** [inertiajs/inertia-laravel#346]
I recently upgraded to  v0.5.1 from an older version. Any `put` requests are not `303`, but instead are `302`. This means it keeps redirecting over and over. I have to manually set the status code to be `303`, whereas prior to  ` v0.5.1` I didn't have to think about that.

**Comment by grantholle** [comment]
If I install `v0.2`, it works as expected using `redirect()`. Anything newer than that it redirects with 302 causing the repeated requests.

Unless I'm missing something new in an update? (I am updating an older app)

**Comment by RobertBoes** [comment]
Inertia-laravel prior to 0.3 registered the middleware automatically, this has drastically changed with 0.3. You'd have to install the middleware and register it yourself, see https://inertiajs.com/releases/inertia-laravel-0.3.0-2020-10-14 for more information

I'd advice to check all the releases for `inertia-laravel` on https://inertiajs.com/releases?all=true from your current version to the one you're updating to. There have been breaking changes and you have to adjust to these changes, otherwise the adapter won't work properly

**Comment by grantholle** [comment]
🤦 Yep! I've done many more projects since then, I just assumed it was already there!

Thanks @RobertBoes
