### ISSUE TITLE
redirect with only

### ISSUE THREAD

**Issue by sbc640964** [inertiajs/inertia-laravel#389]
Greetings

The use of only belongs to requests from js
I would like to do the same in laravel with redirect
Likewise:

```php
back()->withInertiaOnly([])
```

**Comment by Tofandel** [comment]
It might be challenging, redirects are quite restricted in browsers and in this cases it would require the redirect to set a header that then need to be sent back to the redirected page, the problem is that you can't intercept a redirect response in the browser and alter the headers and browsers won't do this by default

So it leaves the option of using a session or some other trick for this to work (which you can do yourself btw)

You can store in the session the `only` you want, with a random id, pass the random id as a query parameter of the redirect and use it to set the header `X-Inertia-Only` of the incoming request and clean up the session

**Comment by sbc640964** [comment]
@Tofandel I will explain my need when to use it.
For example: the customer filled out a form.
The server updates the database, and returns the user to the last address he visited.
The point is, you don't always have to refresh all the data on the page (the decision of what is needed and what is not, is according to the data produced by the server, that is, the logic is in the server, I can't determine it already in sending).

Your idea says: to update in the session the `only` and the relevant call to refer to it and replace the header on the server (how do you damage the request class of laravel?).

**Comment by Tofandel** [comment]
> The server updates the database, and returns the user to the last address he visited.
The point is, you don't always have to refresh all the data on the page

You do if it's a redirect, it's like visiting a new page because inertia cannot store the data in between, it also doesn't know that it was a `redirect()->back()` for all intent and purposes it's a redirect to a new page and this is handled like a page visit, so `only` there does not make much sense unless you store the data yourself in a store or something but then I think you're misusing inertia

**Comment by sbc640964** [comment]
Maybe we should really think about the idea of `inertia redirect`
which means that it is not a real redirect but that inertia returns a different address and content.

This is relevant in the cases I wrote above (in particular with the post method)

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
