### ISSUE TITLE
Multiple invocations of AppServiceProvider boot() method on Inertia Render

### ISSUE THREAD

**Issue by ronfuller** [inertiajs/inertia-laravel#393]
Is there a way to prevent Inertia::render from call AppServiceProvider boot() method multiple times in a request?

When invoking from  a simple controller method , adding traces to AppServiceProvider boot() shows the method called 2x during the request.
```php
Route::get('/welcome',function() {
   return Inertia::render('Welcome');
}
```
If you modify the route, with the following , you will only see one invocation of the boot() method.
```php
Route::get('/welcome',function() {
   return response()->json(['status' => 'success']);
}
```

Multiple invocations of the boot method may not be a huge deal except in a modules environment where all the modules boot methods are invoked multiple times.

**Comment by rojtjo** [comment]
Sounds like something else is happening in your app as Inertia does not call the `boot` method of your service providers. Are you sure these calls happen in the same request?

In the past I've had similar issues like this and it turned out to be a combination of a catch-all route and a missing favicon.

**Comment by ronfuller** [comment]
Roj -

Missing favicon was the culprit.

Thanks!

Ron

**Comment by crnkovic** [comment]
@reinink looks like this has been resolved and can be closed 👍
