### ISSUE TITLE
How to Optimize app.js?

### ISSUE THREAD

**Issue by BroJenuel** [inertiajs/inertia-laravel#414]
I think what he meant was that the app size is large. I am working with inertiajs. As the system grows larger the size becomes larger as well. How to maybe optimize it so that it only loads needed js.

In this picture you can see that my app.js is really large, when I am just rendering a new page with hello world p tag on it.
![image](https://user-images.githubusercontent.com/31676163/172506573-3b797a08-1365-42bd-b9b0-6a783cdf4d9e.png)

**Comment by CraniumAdamantium** [comment]
You can split the coee with dynamic import
https://inertiajs.com/client-side-setup here

**Comment by reinink** [comment]
Yes, code splitting is an option, but `12.1MB` is a HUGE file. I have a *very* large Inertia app, with hundreds of pages, and it's still only `1.9MB`, and it compresses down to `398kB`. I'd recommend reviewing all of your dependencies to see which ones you can trim.

Closing this because it's not an issue with the Laravel adapter.

Good luck! 💪
