### ISSUE TITLE
import being imported twice

### ISSUE THREAD

**Issue by CraniumAdamantium** [inertiajs/inertia-laravel#415]
When I declare dynamic import and then use Inertia.visit it reloads the same component.
¿What do I mean?
Well, I have 2 vue files and a navbar
In navbar I define visit a or b
a.vue
import whatever;
b.vue
import whatever;
When I see the js file generated by mix(run production) I can see the same code being imported twice
How can I achieve it being loaded once?
I tried doing it with mix.extract and it's ok(there's no repeated imports), but the file (vendor.js) contains data not related to the view
¿Any ideas?

**Comment by kde99** [comment]
Yes that is intended. When you use .extract() it creates mutliple js files from the code:
- vendor.js: which has vendor code i.e. libraries that you use like vue, intertiajs, etc.
- app.js: which has your code (that is not vendor) like your shared components and other js code you might write
- resources_js_PATH.js files: these are the entry point views that you have (those that are not being imported anywhere and are thus entry points to the app)

So unless you set up all your views as a module then use those there really shouldn't be anything from them in vendor.js so what you see is normal. By default every library function is included in vendor.js so it's pretty big there are things you can do to reduce that though like for some libraries you can use direct imports so the whole library is not gonna end up in vendor.js.

**Comment by kde99** [comment]
I think you have a bit of a misunderstanding about what Inertia is. Inertia is just a layer between your backend and frontend. All inertia does is it transforms your laravel route properties (the array you give to inertia(route, props) in laravel) to json and sends it to your chosen js frontend (vue in your case). Inertia doesn't care about your frontend code. Inertia only cares about getting the data there. 

You really should be looking at webpack's documentation for this, I'm not sure how much you would save though unless you have a ton of packages installed since vendor.js gets cached by the browser so you only need to get that once unless it changes so if your page is used a lot by people maybe it's better than each page being 10 requests.

**Comment by CraniumAdamantium** [comment]
It's not really worth it, I don't even have a page with a lot users (Not even with few)
I just... like it to be really minimal. However what you said is true, this is something more related to webpack. So I'll close the issue, thanks
