### ISSUE TITLE
Share and return back

### ISSUE THREAD

**Issue by timyourivh** [inertiajs/inertia-laravel#448]
I want the generated data from the model to be displayed on the same page after storing a resource.

When I do this:

```php
public function store(Request $request)
{
    $example = Model::create($request);
    
    Inertia::share('generated', $example->generated);

    return redirect()->back(/* 303 */);
}
```

I get redirected back as expected but the shared data won't be present. No 'generated' key with data in `page.props`.

I was surprised finding out it didn't work while a session workaround does work: 

```diff
- Inertia::share('generated', $example->generated);
+ session()->flash('data', ['generated' => $example->generated]);
```
```php
# App\Http\Middleware\HandleInertiaRequests.php
public function share(Request $request)
{
    return array_merge(parent::share(), [
        /* ... */
        'flash' => [
            'data' => fn () => $request->session()->get('data'),
        ],
    ]);
}
```

Now I'm wondering how it's possible the `Inertia::share()` method is not adding the shared data to the redirect back response. If I check `Inertia::getShared()` using `dd()` I can verify the data is present in the controller after the `share()` method  is called but not present in the `page.props`.
Is this by design, am I missing required config or is this a bug?

**Comment by rojtjo** [comment]
This is actually expected behaviour. When redirecting back you're basically making a new request to the previous URL and all the data you share in the current request is never sent to the browser.

Using the session to flash temporary data is the way to go here. If you're only using the data in one place you might want to consider sharing the data from the controller you're redirecting back to instead of sharing it from the middleware. 

```php
public function pageRedirectingBackTo(Request $request)
{
    return Inertia::render('SomePage', [
        'generated' => $request->session()->get('data'),
    ]);
}
```

**Comment by timyourivh** [comment]
If this is intended behavior I will make use of the session. Thanks for the quick response.
