### ISSUE TITLE
[IDEA] Artisan inertia:make command

### ISSUE THREAD

**Issue by kreierson** [inertiajs/inertia-laravel#467]
In a previous project I had used Laravel Livewire. Livewire has an artisan command php artisan livewire:make.

If I did **php artisan livewire:make** ShowPost it would generate the following files:

App\Http\Livewire\ShowPost.php
App\resources\views\livewire\show-post.blade.php

Would be really sweet to get something like this for Inertia.
**php artisan inertia:make ShowPost**
would generate the following

App\Http\Inertia\ShowPost.php
App\resources\js\Pages\ShowPost.vue

Then in the controller have the following already in place
`
public function __invoke(Request $request)
{
     return inertia('ShowPost');
}
`

As I'm writing this I suppose this only makes sense when using invokable controllers.
But maybe passing an additional parameter to the make command when not using invokable.
php artisan make:inertia PostController --method=show which would just create the show method stub in the PostController?

**Comment by rojtjo** [comment]
You would need to figure out which frontend library the project is using since not everyone is using Vue. To do this you could:
- Scan the `package.json` file to determine which Inertia packages are used (what happens if both `@inertiajs/inertia-react` and `@inertiajs/inertia-vue` are in there for some reason?)
- Add an `inertia` config file to define the stack (not a fan of just adding a config file for this)
- Add a flag to the artisan command: `--stack react` (verbose)

The latter would be the option in my opinion, but it does make the command more verbose.

**Comment by reinink** [comment]
Hey neat idea, and definitely something to consider for the future, but I am going to close this for now as it's not an actual bug with the library. Thanks for sharing either way! 💪
