### ISSUE TITLE
[Feature Request] Allow dot notation in render method

### ISSUE THREAD

**Issue by Naoray** [inertiajs/inertia-laravel#48]
It would be nice to use *Laravel*'s default dot notation when passing views in subfolders to the `render()` method.

```php
// currently
return Inertia::render('User/Create');

// proposal: like we are used to in laravel
return Inertia::render('user.create')
```

**Comment by njoguamos** [comment]
This would be nice

**Comment by reinink** [comment]
Blade files are generally lowercase, so I think that makes more sense. Since Javascript components are often title case, I'm not sure this makes sense. I get the desire to be consistent with Laravel, I'm just not convinced adding this extra complexity is worth it.

Thanks for the suggestion either way! 👍

**Comment by Naoray** [comment]
Then what about simply `Inertia::render('User.Create')`? That way you are consistent with laravel dot notation, but still include the title case of Javascript components...
