### ISSUE TITLE
Conditional Use of Template 

### ISSUE THREAD

**Issue by rutvij2292** [inertiajs/inertia-laravel#55]
In current project I need to use layout.blade.php which doesn't have Inertia.js tag i.e. <div id="app" data-page="{{ json_encode($page) }}"></div> integrated. 

But after integrating Intertia.js now I've an error which is $page variable undefined. 

So, is there any way we can use multiple layout file based on condition? 

Thanks,
Rutvij

**Comment by Juhlinus** [comment]
Hello @rutvij2292 ! 

Could you show us what your layout file looks like?

The `@inertia` directive itself is not very complicated. It contains an `app` id so that Vue knows where the root element is, as well as passing the `$page` variable which is passed everytime you create an `Inertia` response(using the facade or the helper.

```php
        $page = [
            'component' => $this->component,
            'props' => $props,
            'url' => $request->getRequestUri(),
            'version' => $this->version,
        ];
```
https://github.com/inertiajs/inertia-laravel/blob/master/src/Response.php#L63-L68

If you would like to use the `@inertia` directive conditionally then I suggest just putting a blade `@if` and `@else` directive to control this, and then just make sure that in your controller that when you want to use Inertia then you use the Inertia facade/helper and when you want to use Blade or something else then you use those directives.

If there's anything that seems complicated or that you would like me to further explain then you can join [our Discord](https://discord.gg/uefcdb) and ask in the `#help` channel. You are of course free to continue the conversation here with me and the others, if you so wish. :)

**Comment by rutvij2292** [comment]
@Juhlinus Thanks for your reply. Yes, I tried but I've to tweak ServiceProvider little bit and it worked.
