### ISSUE TITLE
image upload help

### ISSUE THREAD

**Issue by mangga88d** [inertiajs/inertia-laravel#596]
i am trying to store image to database, i encounter problem using inertia useForm. other things are fine for me for sending form. only file can not be send. 
any help would be good
![Screenshot at Mar 09 18-24-18](https://github.com/inertiajs/inertia-laravel/assets/41167161/7ab2d85f-bcb0-454b-9cd8-265734a55c72)
![Screenshot at Mar 09 19-20-27](https://github.com/inertiajs/inertia-laravel/assets/41167161/aec6a4ce-1d8b-4bfe-9f90-72aba5ca8578)
![Screenshot at Mar 09 19-43-44](https://github.com/inertiajs/inertia-laravel/assets/41167161/bd3b4ec3-d546-42c8-998d-214038c04e77)
![Screenshot at Mar 09 19-53-56](https://github.com/inertiajs/inertia-laravel/assets/41167161/a37f4411-9cf7-4ad5-b8ef-8eb3760e5313)
![Screenshot at Mar 09 20-03-59](https://github.com/inertiajs/inertia-laravel/assets/41167161/45f015f3-29f5-4182-92d1-a8199a68747e)
![Uploading Screenshot at Mar 10 15-02-54.png…]()

**Comment by craigrileyuk** [comment]
Okay, let's get the basics out of the way:

1. This is the repo for `inertia-laravel`. That is the backend bridge of the Inertia project. This repo has nothing to do with the frontend elements like `useForm`
2. If you're having issues performing basic tasks in a project that has thousands of active users, 999,999 times out of a million, it's going to be a coding error on your part. GitHub issues are not the place to ask for coding assistance. They are for reporting issues with the code _in the repo itself_.

So, rather than be overly negative, here's some help:

`form.product_images = productImages.value.push(file)`

The JS `push` function returns the new length of the array you've just pushed to (see: [MDN Array.prototype.push](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push)). So here, you're just saving an integer to `form.product_images`, not the files.

Push first, and then save `productImages.value` to `form.product_images`.

`form.post` only takes two params, (1) route (2) navigation options object. You need your `onSuccess` in the same object as `preserveState`.

Both Vue and Inertia have Discord channels which will be a more appropriate venue for coding help in the future.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
