### ISSUE TITLE
HTTP testing fails when a custom root view is set: `View [app] not found`

### ISSUE THREAD

**Issue by AndrewFeeney** [inertiajs/inertia-laravel#73]
I think this is happening because the `Inertia\ResponseFactory` class is being instantiated twice during the course of the test, but the rootView property is only reset the first time. We could sort this out by injecting the root view as a nullable constructor parameter and then binding the value of the `$rootView` primitive requested by the Responsable class in the `setRootView()` method.

If this solution makes sense I can put together a PR.

**Comment by AndrewFeeney** [comment]
Closing as I realised the problem was I was setting the root view in the `boot()` method of my `AppServiceProvider` instead of the `register()` method

**Comment by AndrewFeeney** [comment]
Reopening as I realised that didn't actually fix the problem.

**Comment by AndrewFeeney** [comment]
Here's a repo which replicates it.

https://github.com/AndrewFeeney/inertia-custom-root-view-test

**Comment by rojtjo** [comment]
It looks like this is caused due to the `ResponseFactory` not being bound to the container as a singleton. Note, it only happens during testing.

The reason it only happens during testing is because in the `setUp` method of the default Laravel test case it first creates the Application (including registering and booting all service providers) and afterwards [clears all resolved instances from the Facade](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Testing/TestCase.php#L88). Since the Facade normally [caches the resolved instance](https://github.com/laravel/framework/blob/master/src/Illuminate/Support/Facades/Facade.php#L165-L178) it does not return the same instance after clearing because the `ReponseFactory` is not bound as a singleton in the container.
