### ISSUE TITLE
Larvel Dusk tests

### ISSUE THREAD

**Issue by stefro** [inertiajs/inertia-laravel#83]
Hi,

I would like to make Laravel Dusk tests for a Laravel/Inertia app. The thing that doesn't seem to work is that the test steps don't seem to have knowledge of page-changes (I think). 
When I build in a pause after a button press, the tests seem to work, but this is really very clunky and the pause time depends on the speed of the CPU where the tests are running.

Example:
```PHP
    /**
     * @test
     */
    public function wrong_password()
    {
        $user = factory(User::class)->create();

        $this->browse(function (Browser $browser) use ($user) {
            $browser->visit('/login')
                ->type('email', $user->email)
                ->type('password', 'wrong_password')
                ->press('Login')
                ->pause(1000)
                ->assertSee('These credentials do not match our records.');
        });
    }
```

Is there a better way to **wait** for the moment when the assertions can be made.

**Comment by georgehanson** [comment]
Laravel Dusk has a feature to wait until an element is visible by passing a query selector. For example:

```php
$browser->waitFor('.button');
```

You can view the documentation here for more examples - https://laravel.com/docs/5.8/dusk#waiting-for-elements

**Comment by stefro** [comment]
hi @georgehanson. Thanks for your reply!
Yes I was already aware of that. I can try to find an element for each test case to wait for, but I'm actually curious if there is a generic element to wait for. Like the same element in each test. This would make everything much easier.

Since I'm sure I'm not the only one who uses Dusk, I interested to find out how other Inertia users handle this.

**Comment by Sinnbeck** [comment]
Haven't tested but, you might be able to listen for nprogress to disapear

```
$browser->waitUntilMissing('#nprogress');
```

**Comment by stefro** [comment]
Thanks @Sinnbeck !
I've tried it and it works!

**Comment by Sinnbeck** [comment]
Started implementing dusk in my current project and I am also running into issues. I am using a custom .env.dusk.local file with the proper settings. It works for the initial page load, but when changing pages, it seems that dusk is loading the original .env file instead of the new one. I can simply dump my database.default value to the screen (In react), and check the "failed" screenshot

I am unsure if this is a problem with dusk or inertia

**Comment by stefro** [comment]
Thanks for the edit @Sinnbeck .
Good to hear you've figured it out.

**Comment by claudiodekker** [comment]
Looks like this issue's been solved! 

Another solution (I think?) could be to wait for first element inside the inertia-rendered element. Since Vue replaces the whole node tree that it gets mounted on (`#app`, by default in Inertia), it's presence would indicate that your app is ready.

In either case, I'll close this issue for now, but if you feel like it still wasn't answered properly, feel free to re-open the issue at any point by continuing the conversation.

Thanks!

**Comment by xyNNN** [comment]
I want to recommend some package here which helps a lot testing Inertia.js with Laravel Dusk 

https://github.com/protonemedia/inertiajs-events-laravel-dusk

**Comment by riabiy-denis** [comment]
> I want to recommend some package here which helps a lot testing Inertia.js with Laravel Dusk
> 
> https://github.com/protonemedia/inertiajs-events-laravel-dusk

We wrote almost same code, but a bit simpler. Great package. Confirm, that the idea behind that macro works.
