### ISSUE TITLE
Returns an empty array when used with ->only()

### ISSUE THREAD

**Issue by tanthammar** [inertiajs/inertia-laravel#96]
@inertiajs/inertia@0.1.7
@inertiajs/inertia-vue@0.1.2
"inertiajs/inertia-laravel": "^0.2.3",

I am trying to follow the Inertia Docs where `->only()` is used in the examples.
I am confused why I get **empty results** from this query. 
Also why the returned data is **sometimes Array, sometimes Object.**

If I remove `->only()` in the index function below I get 25 `organizers` as an `Object` else I get an empty `Array`.

OrganizerController@index
```php
public function index()
    {
        $query = Auth::user()->hasRole('support') ? new Organizer() : Auth::user()->currentTeam->organizers();

        return Inertia::render('Organizers/Index', [
            'filters' => Request::all('search', 'trashed'),
            'organizers' => $query
                ->orderByTranslation('name')
                ->filter(Request::only('search', 'trashed'))
                ->paginate(),
                ->only('uuid', 'name', 'phone', 'city', 'deleted_at'),  //returns empty array
            'title' => trans('cruds.organizer.title'),
        ]);
    }
```

**Comment by rodrigopedra** [comment]
This is related to Laravel handling the paginated results than Inertia.

When you call `->paginate()` the Query Builder executes the query and creates a `LengthAwarePaginator` object.

The `->only()` call after the `->paginate()` is delegated to the underlying collecttion where it tries to filter the items in the collection with the arguments as keys. As there are none an empty collection is returned.

If you want just to fetch those columns from the organizers model you can try the following:

~~~php
public function index()
    {
        $query = Auth::user()->hasRole('support') ? new Organizer() : Auth::user()->currentTeam->organizers();

        return Inertia::render('Organizers/Index', [
            'filters' => Request::all('search', 'trashed'),
            'organizers' => $query
                ->orderByTranslation('name')
                ->filter(Request::only('search', 'trashed'))
                ->select('uuid', 'name', 'phone', 'city', 'deleted_at') // fetch only the columns you need
                ->paginate(),
            'title' => trans('cruds.organizer.title'),
        ]);
    }
~~~

This way you are telling the query builder to select only those columns.

---

What might have caused the confusion is that the example in the docs uses the `->only()` method that way:

~~~php
// @source https://inertiajs.com/responses#lazy-evaluation
class UsersController extends Controller
{
    public function index()
    {
        return Inertia::render('Users/Index', [
            // Lazily evaluated (only run if required)
            'companies' => function () {
                return Company::orderBy('name')
                    ->get()
                    ->only('id', 'name'); // after DB query, won't work as expected in stock Laravel
            },
            // Evaluated immediately
            'users' => User::orderBy('name')
                ->paginate()
                ->only('id', 'name'), // after DB query, won't work as expected in stock Laravel
        ]);
    }
}
~~~

That won't work as expected when using a stock version. Both results would return an empty array.

This snippet might have find a way to the docs because in the sample app (PingCRM) a custom Paginator is bound to the container:

https://github.com/inertiajs/pingcrm/blob/master/app/Providers/AppServiceProvider.php#L84-L89

In this custom implementation a `->only()` method is added to the paginator.

Considering this you have these choices:

1. Copy the custom paginator to your project
2. Fetch only the columns you need from the DB as I outlined above in the first snippet
3. Transform the results collection after fetching from DB as in the snippet below:

~~~php
public function index()
    {
        $query = Auth::user()->hasRole('support') ? new Organizer() : Auth::user()->currentTeam->organizers();

        return Inertia::render('Organizers/Index', [
            'filters' => Request::all('search', 'trashed'),
            'organizers' => $query
                ->orderByTranslation('name')
                ->filter(Request::only('search', 'trashed'))
                ->paginate()
                ->transform(function ($record) {
                    return $record->only('uuid', 'name', 'phone', 'city', 'deleted_at');
                }),
            'title' => trans('cruds.organizer.title'),
        ]);
    }
~~~

I will also send a PR to fix the docs.

**Comment by rodrigopedra** [comment]
I sent PR https://github.com/inertiajs/inertiajs.com/pull/47 to fix the docs

It generated the following preview:

https://deploy-preview-47--inertiajs.netlify.com/responses#lazy-evaluation

**Comment by reinink** [comment]
Excellent explanation @rodrigopedra, and thanks for the PR. 👍 

Closing this.

**Comment by rodrigopedra** [comment]
Thanks @reinink , glad to help =)

**Comment by tanthammar** [comment]
@rodrigopedra 
Thank You so much for taking the time to give me this extensive and very helpful answer!

**Comment by rodrigopedra** [comment]
@tanthammar  you are welcome, glad to help =)
